Add LG.
melontini/bootloader-unlock-wall-of-shame pull request #21
Opened 2024-09-11 18:59 UTC by Lost-Entrepreneur439

While LG isn't making phones anymore, they're still quite a common phone brand.

2024-09-13 16:16 UTC, melontini requested changes

2024-09-13 16:16 UTC, melontini commented on README.md
> +In the past, LG had a developer portal which could be used to unlock phones on their website, however it only supported international models of their phones, but in December 2021, LG announced the de
> **only if** the phone is a T-Mobile model.

There should be a link to some source.

2024-09-17 16:37 UTC, Lost-Entrepreneur439 commented on README.md
> +In the past, LG had a developer portal which could be used to unlock phones on their website, however it only supported international models of their phones, but in December 2021, LG announced the de
> > **only if** the phone is a T-Mobile model.
> 
> There should be a link to some source.

I added a link to a source on XDA.

2024-09-21 16:02 UTC, melontini approved these changes

2024-09-21 16:02 UTC, merged