Adrres Xiaom global region rumors
melontini/bootloader-unlock-wall-of-shame pull request #31
Opened 2024-10-16 15:53 UTC by lpapadakos

2024-10-16 16:30 UTC, melontini requested changes
Thank you. There's a source issue and some link nitpicks.

2024-10-16 16:30 UTC, melontini commented on brands/xiaomi/README.md
> +[The bootloader CANNOT be unlocked on devices of the Mainland China region](https://gsmchina.com/xiaomi-will-no-longer-allow-bootloader-unlocking-5618/).
I believe that the China thing started ~a month ago, so a more recent article would fit better. This one still talks about the old, short-lived requirements.

2024-10-16 16:30 UTC, melontini commented on brands/xiaomi/README.md
> +[The bootloader CANNOT be unlocked on devices of the Mainland China region](https://gsmchina.com/xiaomi-will-no-longer-allow-bootloader-unlocking-5618/).
This should be a reference link.

e.g. 

```
[The bootloader CANNOT be unlocked on devices of the Mainland China region][bootloader-in-mainland]

...
[Xiaomi-bootloader]:https://github.com/lrh2000/Xiaomi-bootloader
[bootloader-in-mainland]:https://gsmchina.com/xiaomi-will-no-longer-allow-bootloader-unlocking-5618/
```

2024-10-16 16:30 UTC, melontini commented on brands/xiaomi/README.md
> +> Since October 2024 [there have been rumors that Xiaomi will kill bootloader unlocking on the Global market](https://x.com/chunvn8888/status/1841901853073953254), after having done so for the China
This should be a reference link. Also, can be shortened to

```patch
- [there have been rumors that Xiaomi will kill bootloader unlocking on the Global market](https://x.com/chunvn8888/status/1841901853073953254)
+ [there have been rumors][reference-link] that Xiaomi will kill bootloader unlocking on the Global market
```

2024-10-16 17:44 UTC, melontini approved these changes
LGTM.

2024-10-16 17:45 UTC, merged

2025-01-03 00:00 UTC, mirh commented
The surprise is here 
https://xiaomitime.com/xiaomi-global-bootloader-unlock-policy-has-changed-20295/