Update README.md
melontini/bootloader-unlock-wall-of-shame pull request #33
Opened 2024-10-19 09:51 UTC by czl92783719

2024-10-19 09:52 UTC, czl92783719 commented
This method helps much and I used this and successfully unlocked my Kirn 710 based nova 4e🤩🤩🤩🤩🤩🤩

2024-10-19 09:57 UTC, czl92783719 commented
dont forget to remove the battery between the two times of testpoint mode entering

2024-10-25 15:01 UTC, melontini requested changes

2024-10-25 15:01 UTC, melontini commented on brands/huawei/README.md
> +Certain Kirin-based phones can use [PotatoNV], and some of others can use [this method](https://xdaforums.com/t/free-huawei-kirin-bootloader-and-frp-unlocking-through-test-point-2024.4673890/)
The source is a bit dubious. The "Android Utility" link is nowhere to be found, and there aren't that many success messages.

2024-11-17 12:16 UTC, closed without merging