add itel
melontini/bootloader-unlock-wall-of-shame pull request #50
Opened 2024-11-17 00:49 UTC by Lost-Entrepreneur439

2024-11-17 15:26 UTC, melontini requested changes

2024-11-17 15:26 UTC, melontini commented on brands/itel/README.md
> +it el follows the [standard unlock procedure](/misc/general-unlock.md) for their MediaTek devices, and the [Unisoc procedure][Unisoc Unlock] for their Unisoc devices.
```suggestion
itel follows the [standard unlock procedure](/misc/general-unlock.md) for their MediaTek devices, and the [Unisoc procedure][Unisoc Unlock] for their Unisoc devices.
```

2024-11-17 19:28 UTC, Lost-Entrepreneur439 commented on brands/itel/README.md
> +it el follows the [standard unlock procedure](/misc/general-unlock.md) for their MediaTek devices, and the [Unisoc procedure][Unisoc Unlock] for their Unisoc devices.
fixed

2024-11-18 13:58 UTC, melontini approved these changes

2024-11-18 13:58 UTC, merged