Add page for carriers
melontini/bootloader-unlock-wall-of-shame pull request #57
Opened 2024-12-03 14:25 UTC by Lost-Entrepreneur439

This page is probably going to need a few modifications before it can be merged.

I put in as much info as I can, however I couldn't do much as I'm from Canada (where carrier locking is illegal), and it's a lot harder to find details about carriers than it is phone manufacturers, most of my info is going off what I know from American friends, so there's a lot more carriers that could be added to this page.

2024-12-06 17:05 UTC, melontini reviewed
I feel that this should be split into pages. Similar to brands.

2025-01-15 14:36 UTC, Lost-Entrepreneur439 commented
> I feel that this should be split into pages. Similar to brands.

Done

2025-01-19 14:43 UTC, melontini requested changes
I'll assume that the info is correct. There are some individual issues with formatting, and pages should have a `#` header at the top.

2025-01-19 14:43 UTC, melontini commented on carriers/brands/tmobile/README.md
> +Do note that this does *not* account for phones made by T-Mobile, these phones have a number of different OEMs, usually Wingtech for newer models, and [HTC](/brands/htc/README.md) for older models, h
No footer on this page

2025-01-19 14:43 UTC, melontini commented on carriers/brands/boost/README.md
> +Boost doesn't have a wide choice of Android phones, they only have Samsung, Motorola, and phones made by Boost (likely made by a different OEM, similar to T-Mobile, I can't find which OEM though). I
The link is broken

2025-01-20 18:06 UTC, Lost-Entrepreneur439 commented on carriers/brands/boost/README.md
> +Boost doesn't have a wide choice of Android phones, they only have Samsung, Motorola, and phones made by Boost (likely made by a different OEM, similar to T-Mobile, I can't find which OEM though). I
Fixed

2025-01-21 13:45 UTC, melontini approved these changes
LGTM. Thank you for your work

2025-01-21 13:46 UTC, merged