Add new Xiaomi policy changes.
melontini/bootloader-unlock-wall-of-shame pull request #64
Opened 2024-12-30 22:02 UTC by AngelCMHxD

After January 1, 2025, Xiaomi will further reduce the amount of devices you can unlock to 1 device per year per account.

This PR adds this information to Xiaomi's README file, warning users about this change along with an image showing the policy changes.

An image was linked (mostly as a placeholder) as this information isn't available on a website by Xiaomi but instead available on the Xiaomi Community app when applying for unlocking, however if a better alternative to this (or anything, really) is recommended I'm open to switching to it.

2025-01-02 12:02 UTC, melontini requested changes
Since it's already January 2025, this should be merged into the main body of the text.

LG otherwise. Maybe "but got reduced" sounds a bit off.

2025-01-02 19:32 UTC, AngelCMHxD commented
In the latest commit I've merged the info into the main body of the text in a way which seemed the best way to do it. A review is still greatly appreciated.

2025-01-03 00:03 UTC, mirh commented
Maybe linking the article directly would be better?

2025-01-03 04:35 UTC, AngelCMHxD commented
At first I thought of keeping the tweet as it summarizes all of the article, however the first paragraph of the article also provides a good sum up and linking it directly reduces the amount of clicks needed to get to the full information. Changing it in a second and thanks for the suggestion! :P

2025-01-03 12:13 UTC, melontini requested changes

2025-01-03 12:13 UTC, melontini commented on brands/xiaomi/README.md
> +* ~~You can only unlock the bootloader of 3 devices per year with your account.~~
Please don't do this. We have the commit history for stuff like this.

2025-01-03 12:13 UTC, melontini commented on brands/xiaomi/README.md
> +Xiaomi has [updated their policies][updated-policies], further restricting bootloader unlocking. As of January 1st, 2025, they only let you unlock 1 device per year. *What a good way to start the yea
This should be part of the list instead.

2025-01-03 14:14 UTC, AngelCMHxD commented
Addressed the comments in the latest commit! Anything else that could be improved?

2025-01-03 15:08 UTC, melontini approved these changes
LGTM, thank you

2025-01-03 15:15 UTC, merged

2025-01-03 15:16 UTC, mirh commented
Random showerthought: isn't the the requirement more technically correct be written as "unlock 1 device per account per year"?
(be it as it may that idk what kinds of limitations a device may have, to switching accounts).

Btw you are forgetting the part of the procedure that [obliges](https://xiaomi.eu/community/threads/unlock-bootloader-without-sim.50796/) you to have a SIM ([supposedly](https://xdaforums.com/t/about-unlocking-the-bootloader.4575327/) it's only needed on devices which do have a slot to begin with)

2025-01-03 15:44 UTC, melontini commented
Good point about the SIM requirement. I'll address this myself a bit later.

As per the device thing, uh, I'm not sure? The account part is true, but does this matter in practice? I'll update that too, but it'd be nice to know how account switching is handled.

2025-01-03 15:48 UTC, mirh commented
I mean, I'm just pitching guesses, never had a xiaomi.
In "they only let ***you*** unlock 1 device" the pronoun does a lot of heavy lifting.

2025-01-03 17:50 UTC, AngelCMHxD commented
Afaik, if you try to bypass the restriction you may be ban

2025-01-06 19:35 UTC, mirh commented
You mean like changing to a fresh account right when you need a new unlock?
Surely they cannot just ban you just for that?